@OOTPnSP.Laba3_HostAddress = http://localhost:5237

POST {{OOTPnSP.Laba3_HostAddress}}/editor/
Content-Type: application/json

{
  "X": 1250,
  "Y": 200,
  "BottomSide": 40,
  "LeftSide": 30,
  "Angle": 30,
  "TypeOfFactory": "parallelogram"
}

###
